name: Dependency Caching Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-with-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-e998795-${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            cache-e998795-${{ runner.os }}-pip-
      
      - name: prime-cache-e998795
        run: |
          echo "=== Cache Status Report ==="
          if [[ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]]; then
            echo "✓ Cache hit! Dependencies were restored from cache."
            echo "Cache was successfully restored from previous run."
          else
            echo "✗ Cache miss! Dependencies will be downloaded and cached."
            echo "This is normal on the first run or when requirements change."
          fi
          echo "Cache hit value: ${{ steps.cache-deps.outputs.cache-hit }}"
          echo "==========================="
      
      - name: Create requirements.txt if missing
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requests==2.31.0" > requirements.txt
            echo "pandas==2.1.0" >> requirements.txt
            echo "numpy==1.24.3" >> requirements.txt
          fi
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Verify installation
        run: |
          echo "Testing installed packages..."
          python -c "import requests; print('✓ requests version:', requests.__version__)"
          python -c "import pandas; print('✓ pandas version:', pandas.__version__)"
          python -c "import numpy; print('✓ numpy version:', numpy.__version__)"
          echo "All packages imported successfully!"
